
sudo: required
dist: trusty
language: csharp

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends dotnet-sdk-2.0.0
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install semver -g

before_script:
  - chmod u+x build.sh
  - chmod u+x ./scripts/set-build-version.sh
  - eval $(./scripts/set-build-version.sh)
  - export PATH=$PATH:$HOME/.local/bin
  - mono --version
  - dotnet --info

script:
  - ./build.sh --version=$PROJECT_BUILD_VERSION --configuration=RELEASE