apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sqlserver-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sqlserver-db
        image: microsoft/mssql-server-linux:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: Passw0rd
status: {}