apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: tugberk-web
  name: tugberk-web
spec:
  ports:
  - port: 80
    name: 'web-app-port'
    protocol: TCP
    targetPort: 5000
  - port: 1433
    name: 'sqlserver-port'
    protocol: TCP
    targetPort: 1433
  selector:
    run: tugberk-web
  type: LoadBalancer
status:
  loadBalancer: {}
